**Task_1** Load Libraries and Data

In [28]:
# Import the numpy and pandas libraries.
import numpy as np
import pandas as pd

# Read the data file into a DataFrame named df.
df = pd.read_csv('/workspaces/Data-Cleaning-Project/data/raw data/Cafe Sales.csv')

**Task_2** Intial Data Inspection

In [29]:
# Inspect the first 5 rows using .head().
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [30]:
# Inspect the last 5 rows using .tail().
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [31]:
# Get a summary of the DataFrame, including data types and non-null counts, using .info().
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

Task_3 Check for Duplicates

In [32]:
# Check for any complete duplicate rows.
print(f' Number Of Duplicate Record : {sum(df.duplicated())}')

 Number Of Duplicate Record : 0

**Task_4** Identify Bad and Missing Data

In [33]:
# Calculating  the percentage of missing values for each column.
df.isna().sum()*100/df.shape[0]

Transaction ID       0.00
Item                 3.33
Quantity             1.38
Price Per Unit       1.79
Total Spent          1.73
Payment Method      25.79
Location            32.65
Transaction Date     1.59
dtype: float64

In [34]:
# Identifying the unique values in the categorical columns.
df_column = set(df.columns)
exclude = {'Transiaction ID'}
df_column = df_column.difference(exclude)
for column in df_column:
   print(f'{column}: \n{df[column].unique()}', end='\n\n')

Price Per Unit:
<StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str

Payment Method:
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

Total Spent:
<StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

Item:
<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

Location:
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

Transaction Date:
<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
 ...
 '2023-08-01', '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
 '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
Length: 368, dtype: str

Quantity:
<StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str

Transaction ID:
<StringArray>
['TXN_1961373', 'TXN_4977031', 'TXN_4271903', 'TXN_7034554', 'TXN_3160411',
 'TXN_2602893', 'TXN_4433211', 'TXN_6699534', 'TXN_4717867', 'TXN_2064365',
 ...
 'TXN_1538510', 'TXN_3897619', 'TXN_2739140', 'TXN_4766549', 'TXN_7851634',
 'TXN_7672686', 'TXN_9659401', 'TXN_5255387', 'TXN_7695629', 'TXN_6170729']
Length: 10000, dtype: str

**Task_5** Clean Bad Values

In [35]:
# Replacing all instances of 'ERROR' and 'UNKNOWN' across the entire DataFrame.
df = df.replace(['ERROR', 'UNKNOWN'], np.nan)

In [36]:
# Percentage of missing values after replacing by NaN.
df.isna().sum()*100/df.shape[0]

Transaction ID       0.00
Item                 9.69
Quantity             4.79
Price Per Unit       5.33
Total Spent          5.02
Payment Method      31.78
Location            39.61
Transaction Date     4.60
dtype: float64

**Task_6** Correct Data Type

In [37]:
# Converting the 'Quantity' column to the 'Int64' type.
df['Quantity'] = df['Quantity'].astype('Int64')

# Converting the 'Price Per Unit' and 'Total Spent' columns to the 'float' type.
df[['Price Per Unit', 'Total Spent']] = df[['Price Per Unit', 'Total Spent']].astype(float)

# Converting the 'Transaction Date' column to 'datetime' type.
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   Int64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 634.9 KB

**Task_7** Handle Missing Data

In [38]:
# Drop any rows where 'Transaction Date' is missing.
df = df.dropna(subset= 'Transaction Date')
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              8613 non-null   str
 2   Quantity          9086 non-null   Int64
 3   Price Per Unit    9034 non-null   float64
 4   Total Spent       9064 non-null   float64
 5   Payment Method    6525 non-null   str
 6   Location          5761 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [39]:
# Fill missing values in 'Payment Method' and 'Location' with the placeholder string 'INA'.
df[['Payment Method', 'Location']] = df[['Payment Method', 'Location']].fillna('INA')
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              8613 non-null   str
 2   Quantity          9086 non-null   Int64
 3   Price Per Unit    9034 non-null   float64
 4   Total Spent       9064 non-null   float64
 5   Payment Method    9540 non-null   str
 6   Location          9540 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [40]:
# Fill missing 'Item' values with the mode.
df['Item'] = df['Item'].fillna(df['Item'].mode()[0])
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              9540 non-null   str
 2   Quantity          9086 non-null   Int64
 3   Price Per Unit    9034 non-null   float64
 4   Total Spent       9064 non-null   float64
 5   Payment Method    9540 non-null   str
 6   Location          9540 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [41]:
df.describe()

       Quantity  Price Per Unit  Total Spent            Transaction Date
count    9086.0     9034.000000  9064.000000                        9540
mean   3.025314        2.950022     8.914442  2023-07-01 23:00:31.698113
min         1.0        1.000000     1.000000         2023-01-01 00:00:00
25%         2.0        2.000000     4.000000         2023-04-01 00:00:00
50%         3.0        3.000000     8.000000         2023-07-02 00:00:00
75%         4.0        4.000000    12.000000         2023-10-02 00:00:00
max         5.0        5.000000    25.000000         2023-12-31 00:00:00
std     1.41834        1.277750     6.010311                         NaN

In [42]:
# Fill missing 'Quantity' values with the median.
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              9540 non-null   str
 2   Quantity          9540 non-null   Int64
 3   Price Per Unit    9034 non-null   float64
 4   Total Spent       9064 non-null   float64
 5   Payment Method    9540 non-null   str
 6   Location          9540 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [43]:
df.groupby('Item')['Price Per Unit'].value_counts()

Item      Price Per Unit
Cake      3.0               1031
Coffee    2.0               1069
Cookie    1.0                976
Juice     3.0               1288
          4.0                202
          2.0                116
          5.0                115
          1.0                112
          1.5                108
Salad     5.0               1035
Sandwich  4.0               1027
Smoothie  4.0                990
Tea       1.5                965
Name: count, dtype: int64

In [47]:
# Filling NaNs with the mode of each item's price.
df['Price Per Unit'] = df.groupby('Item')['Price Per Unit'].transform(lambda x : x.fillna(x.mode()[0]))
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              9540 non-null   str
 2   Quantity          9540 non-null   Int64
 3   Price Per Unit    9540 non-null   float64
 4   Total Spent       9540 non-null   float64
 5   Payment Method    9540 non-null   str
 6   Location          9540 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [45]:
# Filling 'Total Spent' values by calculating (Quantity * Price Per Unit)
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              9540 non-null   str
 2   Quantity          9540 non-null   Int64
 3   Price Per Unit    9540 non-null   float64
 4   Total Spent       9540 non-null   float64
 5   Payment Method    9540 non-null   str
 6   Location          9540 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

Task_8 Save the Cleaned Dataset

In [46]:
# Save the final, cleaned DataFrame to a new CSV file.
df. to_csv('/workspaces/Data-Cleaning-Project/data/raw data/processed/Cafe Sales (clened).csv')